## Aponti Academy - Indicadores e Fatores Associados a Acidentes de Trânsito 2025

### Base de Acidentes (Acidentes2025.csv)

#### Módulo 6:

Análise Exploratória, Indicadores e Fatores Associados para um contexto de análise de dados em acidentes de trânsito com indicadores - Ranking e séries - análise bivarida orientada a um alvo com combinações de fatores gráficos e síntese interpretativa

 #### Base de dados:

com cerca de 72529 acidentes, nós periodos de 2025-01-01 a 2025-11-02, apresento as seguintes colunas na base de dados

- id = Identificador único do acidente na base de dados.
- data_inversa = Data da ocorrência do acidente.
- dia_semana = Dia da semana em que ocorreu o acidente.
- horario = Horário da ocorrência.
- uf = Unidade da Federação onde ocorreu o acidente.
- br = Rodovia federal onde ocorreu o acidente.
- km = Quilômetro aproximado do acidente.
- municipio = Município onde ocorreu o acidente.
- fase_dia = Fase do dia em que ocorreu o acidente.
- sentido_via = Sentido da via no local do acidente.

- pessoas = Quantidade de pessoas envolvidas no acidente.
- mortos = Quantidade de mortos.
- feridos_leves = Quantidade de feridos leves.
- feridos_graves = Quantidade de feridos graves.
- ilesos = Quantidade de pessoas ilesas.
- feridos = Quantidade total de feridos.
- veiculos = Quantidade de veículos envolvidos no acidente.
- regional = Regional responsável pelo atendimento.
- delegacia = Delegacia responsável pelo atendimento.
- uop = Unidade Operacional responsável pelo atendimento.

#### Problema analítico central

- Como as variáveis temporais (data, horário e dia da semana), administrativas (UF, BR e regional), características da via (sentido da via) e características da ocorrência (quantidade de veículos e pessoas) se relacionam com os acidentes registrados pela Polícia Rodoviária Federal em 2025?

#### Objetivo Geral

Analisar os fatores temporais, ambientais, estruturais e geográficos associados aos acidentes registrados pela Polícia Rodoviária Federal em 2025, identificando padrões que contribuam para a compreensão da frequência, do tipo e da gravidade das ocorrências.

#### Importação das bibliotecas

In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt

#### Importação do módulo de formatação de eixos do matplotlib

In [3]:
# Usado para exibir os eixos dos gráficos em formato de porcentagem (%), facilitando a leitura 
import matplotlib.ticker as mtick

In [4]:
# Configuração de exibição de números decimais do pandas 
# Formata todos os números float exibidos em tabelas com separador de milhar e 2 casas decimais 
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

In [5]:
# Ajuste da resolução (DPI) padrão dos gráficos 
# Deixa os gráficos exibidos no notebook com melhor nitidez 
plt.rcParams["figure.dpi"] = 100

In [6]:
# Leitura do arquivo csv da base de dados 
# Carrega os 72530 registros de acidentes para o dataframe chamado "prf_acidentes_2025"
prf_acidentes_2025 = pd.read_csv("acidentes2025.csv", encoding="ISO-8859-1", sep=";")

In [7]:
# Conversão da coluna de data de texto para o tipo datetime 
# Necessário para permitir agrupamento por mês / ano e cálculos de série temporal 
prf_acidentes_2025["data_inversa"] = pd.to_datetime(prf_acidentes_2025["data_inversa"])

In [8]:
# Exibição do formato da base (linhas, colunas) 
# Primeira conferência: confirma que os 72530 acidentes e as 30 colunas foram carregados corretamente 
print(prf_acidentes_2025.shape)

(72529, 30)

In [9]:
# Exibição das 10 primeiras linhas da base 
# Permite uma inspeção visual inicial da estrutura e do contéudo dos dados 
prf_acidentes_2025.head(10)

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,652493,2025-01-01,quarta-feira,06:20:00,SP,116,225,GUARULHOS,Reação tardia ou ineficiente do condutor,Tombamento,...,0,0,1,1,2,"-23,48586772","-46,54075317",SPRF-SP,DEL01-SP,UOP01-DEL01-SP
1,652519,2025-01-01,quarta-feira,07:50:00,CE,116,"546,2",PENAFORTE,Pista esburacada,Colisão frontal,...,0,1,4,1,6,"-7,812288","-39,08333306",SPRF-CE,DEL05-CE,UOP03-DEL05-CE
2,652522,2025-01-01,quarta-feira,08:45:00,PR,369,"88,2",CORNELIO PROCOPIO,Reação tardia ou ineficiente do condutor,Colisão traseira,...,0,2,0,3,2,"-23,182565","-50,637228",SPRF-PR,DEL07-PR,UOP05-DEL07-PR
3,652544,2025-01-01,quarta-feira,11:00:00,PR,116,74,CAMPINA GRANDE DO SUL,Reação tardia ou ineficiente do condutor,Saída de leito carroçável,...,0,4,0,1,2,"-25,36517687","-49,04223028",SPRF-PR,DEL01-PR,UOP02-DEL01-PR
4,652549,2025-01-01,quarta-feira,09:30:00,MG,251,471,FRANCISCO SA,Velocidade Incompatível,Colisão frontal,...,1,1,2,2,4,"-16,46801304","-43,43121303",SPRF-MG,DEL12-MG,UOP01-DEL12-MG
5,652569,2025-01-01,quarta-feira,10:40:00,MT,70,669,CACERES,Transitar na contramão,Colisão frontal,...,0,1,2,0,5,"-16,04148578","-57,25884017",SPRF-MT,DEL03-MT,UOP02-DEL03-MT
6,652573,2025-01-01,quarta-feira,12:23:00,RS,116,376,TAPES,Ausência de reação do condutor,Saída de leito carroçável,...,0,0,1,1,2,"-30,739714","-51,62594",SPRF-RS,DEL02-RS,UOP02-DEL02-RS
7,652617,2025-01-01,quarta-feira,17:45:00,SC,101,"207,4",SAO JOSE,Ausência de reação do condutor,Colisão traseira,...,0,1,0,1,2,"-27,60001226","-48,6226467",SPRF-SC,DEL01-SC,UOP01-DEL01-SC
8,652625,2025-01-01,quarta-feira,18:40:00,MG,116,"708,5",MURIAE,Velocidade Incompatível,Tombamento,...,0,0,1,0,2,"-21,16328873","-42,37968988",SPRF-MG,DEL07-MG,UOP02-DEL07-MG
9,652648,2025-01-01,quarta-feira,17:00:00,PE,407,"7,4",AFRANIO,Demais falhas mecânicas ou elétricas,Incêndio,...,0,2,0,0,1,"-8,47503105","-41,0137105",SPRF-PE,DEL06-PE,UOP02-DEL06-PE

#### Compreensão dos dados

- Antes de qualquer indicador, conferimos tipos, nulos e consistência - equivalente ao Bloco "Compreensão dos dados" do CRISP-DM que antecede este módulo.

In [10]:
# Exibição dos tipos de dados (dtype) de cada coluna. 
# Importante para confirmar se colunas numéricas (preço, quantidade) e de data foram 
# reconhecidos corretamente, e não interpretadas como texto (object) 

print("Tipos de dados: ") 
print(prf_acidentes_2025.dtypes)

Tipos de dados:
id                                 int64
data_inversa              datetime64[us]
dia_semana                           str
horario                              str
uf                                   str
br                                 int64
km                                   str
municipio                            str
causa_acidente                       str
tipo_acidente                        str
classificacao_acidente               str
fase_dia                             str
sentido_via                          str
condicao_metereologica               str
tipo_pista                           str
tracado_via                          str
uso_solo                             str
pessoas                            int64
mortos                             int64
feridos_leves                      int64
feridos_graves                     int64
ilesos                             int64
ignorados                          int64
feridos                            int64
veiculos                           int64
latitude                             str
longitude                            str
regional                             str
delegacia                            str
uop                                  str
dtype: object

In [11]:
# Contagem de valores ausentes (NaN) por coluna 
# Etapa obrigatória de qualidade de dados: identifica onde existem lacunas 
# antes de calcular qualquer indicador ou média 
print("\n Valores ausentes por coluna: ") 
print(prf_acidentes_2025.isna().sum())

 Valores ausentes por coluna:
id                         0
data_inversa               0
dia_semana                 0
horario                    0
uf                         0
br                         0
km                         0
municipio                  0
causa_acidente             0
tipo_acidente              0
classificacao_acidente     1
fase_dia                   0
sentido_via                0
condicao_metereologica     0
tipo_pista                 0
tracado_via                0
uso_solo                   0
pessoas                    0
mortos                     0
feridos_leves              0
feridos_graves             0
ilesos                     0
ignorados                  0
feridos                    0
veiculos                   0
latitude                   0
longitude                  0
regional                   2
delegacia                 22
uop                       38
dtype: int64

In [12]:
# Verificação do périodo coberto pela base 
# Mostra a menor e a maior data de acidente, delimitanto a janela temporal da análise 
print("\n Período coberto: ", prf_acidentes_2025['data_inversa'].min().date(), "a", prf_acidentes_2025["data_inversa"].max().date())

 Período coberto:  2025-01-01 a 2025-12-31

#### Status dos Acidentes com as colunas

- dia_semana
- horario
- fase_dia
- sentido_via
- uf
- br
- veiculos
- pessoas

In [13]:
# Contagem de acidentes por dia da semana
# Primeira visão da variável que originará o alvo (pedido_problematico):
# quantos acidentes possui a parte de dia da semana
print("\nStatus de Acidentes por dia da semana")
print(prf_acidentes_2025["dia_semana"].value_counts())

Status de Acidentes por dia da semana
dia_semana
sábado           11554
domingo          11470
sexta-feira      11197
segunda-feira    10285
quarta-feira      9556
quinta-feira      9405
terça-feira       9062
Name: count, dtype: int64

In [14]:
# Contagem de acidentes por horário
# Primeira visão da variável que originará o alvo (pedido_problematico):
# quantos acidentes possui a parte de horário
print("\nStatus de Acidentes por horário")
print(prf_acidentes_2025["horario"].value_counts())

Status de Acidentes por horário
horario
19:00:00    1060
18:30:00     982
18:00:00     965
17:00:00     886
08:00:00     837
            ...
03:52:00       1
02:59:00       1
04:27:00       1
04:37:00       1
03:32:00       1
Name: count, Length: 1412, dtype: int64

In [15]:
# Contagem de acidentes por fase do dia
# Primeira visão da variável que originará o alvo (pedido_problematico):
# quantos acidentes possui a parte de fase do dia
print("\nStatus de Acidentes por fase do dia")
print(prf_acidentes_2025["fase_dia"].value_counts())

Status de Acidentes por fase do dia
fase_dia
Pleno dia      40375
Plena Noite    24781
Anoitecer       3926
Amanhecer       3447
Name: count, dtype: int64

In [16]:
# Contagem de acidentes por sentido da via
# Primeira visão da variável que originará o alvo (pedido_problematico):
# quantos acidentes possui a parte de sentido da via
print("\nStatus de Acidentes por sentido da via")
print(prf_acidentes_2025["sentido_via"].value_counts())

Status de Acidentes por sentido da via
sentido_via
Crescente        38715
Decrescente      33647
Não Informado      167
Name: count, dtype: int64

In [17]:
# Contagem de acidentes por UF
# Primeira visão da variável que originará o alvo (pedido_problematico):
# quantos acidentes possui a parte de UF
print("\nStatus de Acidentes por UF")
print(prf_acidentes_2025["uf"].value_counts())

Status de Acidentes por UF
uf
MG    9570
SC    8186
PR    7630
RJ    6428
RS    4899
SP    4683
BA    4108
GO    3196
PE    3013
ES    2642
MT    2636
PB    1978
MS    1654
RN    1648
PI    1490
RO    1452
CE    1302
MA    1262
PA    1117
DF    1011
TO     677
AL     629
SE     589
AC     280
AP     169
RR     142
AM     138
Name: count, dtype: int64

In [18]:
# Contagem de acidentes por BR
# Primeira visão da variável que originará o alvo (pedido_problematico):
# quantos acidentes possui a parte de BR
print("\nStatus de Acidentes por BR")
print(prf_acidentes_2025["br"].value_counts())

Status de Acidentes por BR
br
101    13014
116    11021
40      3502
381     3496
153     2789
       ...
484        1
431        1
437        1
430        1
426        1
Name: count, Length: 115, dtype: int64

In [19]:
# Contagem de acidentes por quantidade de veículos
# Primeira visão da variável que originará o alvo (pedido_problematico):
# quantos acidentes possui a parte de quantidade de veículos
print("\nStatus de Acidentes por quantidade de veículos")
print(prf_acidentes_2025["veiculos"].value_counts())

Status de Acidentes por quantidade de veículos
veiculos
2     35070
1     23617
3      8623
4      3002
5      1285
6       437
7       224
8       114
9        68
10       23
11       22
12       16
13       14
14        5
18        2
15        2
16        1
21        1
82        1
17        1
31        1
Name: count, dtype: int64

#### Bloco 1 - Base tratada aos indicadores

- Objetivo: revisar a base e criar os indicadores essenciais.

* Pergunta: O que a base permite medir?


* Saida: Tabela de indicadores globais.

In [20]:
prf_acidentes_2025["acidente_grave"] = prf_acidentes_2025["classificacao_acidente"].isin(["Com Vítimas Fatais", "Com Vítimas Feridas"]).astype(int)
prf_acidentes_2025["acidente_fatal"] = (prf_acidentes_2025["classificacao_acidente"] == "Com Vítimas Fatais").astype(int)

In [21]:
### Acidente no período noturno
prf_acidentes_2025["periodo_noturno"] = prf_acidentes_2025["fase_dia"].isin(["Plena Noite", "Anoitecer", "Amanhecer"]).astype(int)

In [22]:
### Acidente em fim de semana
prf_acidentes_2025["fim_semana"] = prf_acidentes_2025["dia_semana"].isin(["sábado", "domingo"]).astype(int)

In [23]:
### Acidente com múltiplos veículos
prf_acidentes_2025["multiplos_veiculos"] = (prf_acidentes_2025["veiculos"] >= 2).astype(int)

In [24]:
### Acidente com muitas pessoas envolvidas
prf_acidentes_2025["muitas_pessoas"] = (prf_acidentes_2025["pessoas"] >= 4).astype(int)

#### Cálculo dos indicadores

In [25]:
### Total de acidentes 
total_acidentes = len(prf_acidentes_2025)

In [26]:
### Acidentes Graves 
acidentes_graves = prf_acidentes_2025["acidente_grave"].sum()

In [27]:
acidentes_fatais = (
    
    prf_acidentes_2025["classificacao_acidente"] == "Com Vítimas Fatais"
).sum()

In [28]:
### Acidentes no Período Noturno
acidentes_periodo_noturno = prf_acidentes_2025["periodo_noturno"].sum()

In [29]:
### Acidentes em Finais de Semana
acidentes_fim_semana = prf_acidentes_2025["fim_semana"].sum()

In [30]:
### Acidentes com Múltiplos Veículos
acidentes_multiplos_veiculos = prf_acidentes_2025["multiplos_veiculos"].sum()

In [31]:
pct_graves = acidentes_graves / total_acidentes

In [32]:
pct_fatais = acidentes_fatais / total_acidentes

#### Tabela Resumo

In [33]:
indicadores_globais = pd.DataFrame({
    "Indicador": [
        "Total de acidentes",
        "Acidentes graves",
        "% de acidentes graves",
        "Acidentes fatais",
        "Acidentes no período noturno",
        "Acidentes em finais de semana",
        "Acidentes com múltiplos veículos"
    ],
    "Valor": [
        total_acidentes,
        acidentes_graves,
        pct_graves,
        acidentes_fatais,
        acidentes_periodo_noturno,
        acidentes_fim_semana,
        acidentes_multiplos_veiculos
    ]
})

In [34]:
indicadores_globais

                          Indicador     Valor
0                Total de acidentes 72,529.00
1                  Acidentes graves 61,390.00
2             % de acidentes graves      0.85
3                  Acidentes fatais  5,209.00
4      Acidentes no período noturno 32,154.00
5     Acidentes em finais de semana 23,024.00
6  Acidentes com múltiplos veículos 48,912.00

- Leitura: Os indicadores globais de acidentes representam a linha de base (baseline) da análise. Eles monstram o panorama geral da ocorrência de acidentes na base de dados e servem como referência para comparar segmentos específicos, como municípios, causas de acidentes, condições meteorológicas, tipos de pista, traçados da via e áreas urbanas ou rurais.

- Por exemplo, a porcentagem global de acidentes graves pode ser comparada com a porcentagem observada em um determinado município ou em uma determinada condição climática para identificar situações de maior risco.

#### Bloco 2 - Frequências, rankings e séries simples

In [67]:
def ranking_dia_semana(var):
    t = (
        prf_acidentes_2025
        .groupby(var)
        .agg(
            acidentes=("dia_semana", "count"),
            acidentes_graves=("acidente_grave", "sum"),
            mortos=("mortos", "sum"),
        )
        .sort_values("acidentes", ascending=False)
    )
    t["pct_acidentes"] = t["acidentes"] / total_acidentes
    t["pct_fatais"] = (
        prf_acidentes_2025.groupby(var)["acidente_fatal"].sum() / t["acidentes"]
    )
    return t

ranking_dia_semana("dia_semana").head(30)

               acidentes  acidentes_graves  mortos  pct_acidentes  pct_fatais
dia_semana
sábado             11554              9515    1120           0.16        0.08
domingo            11470              9319    1183           0.16        0.09
sexta-feira        11197              9591     907           0.15        0.07
segunda-feira      10285              8819     747           0.14        0.06
quarta-feira        9556              8263     711           0.13        0.06
quinta-feira        9405              8042     694           0.13        0.07
terça-feira         9062              7841     681           0.12        0.06

In [68]:
def ranking_horario(var):
    t = (
        prf_acidentes_2025
        .groupby(var)
        .agg(
            acidentes=("horario", "count"),
            acidentes_graves=("acidente_grave", "sum"),
            mortos=("mortos", "sum"),
        )
        .sort_values("acidentes", ascending=False)
    )
    t["pct_acidentes"] = t["acidentes"] / total_acidentes
    t["pct_fatais"] = (
        prf_acidentes_2025.groupby(var)["acidente_fatal"].sum() / t["acidentes"]
    )
    return t

ranking_horario("horario").head(30)

          acidentes  acidentes_graves  mortos  pct_acidentes  pct_fatais
horario
19:00:00       1060               904     102           0.01        0.09
18:30:00        982               852      81           0.01        0.08
18:00:00        965               819      59           0.01        0.05
17:00:00        886               751      75           0.01        0.06
08:00:00        837               738      36           0.01        0.04
20:00:00        803               669      86           0.01        0.09
16:00:00        779               665      52           0.01        0.06
17:30:00        775               670      42           0.01        0.05
07:00:00        770               662      37           0.01        0.04
07:30:00        751               680      38           0.01        0.04
19:30:00        743               640      94           0.01        0.11
15:00:00        743               612      50           0.01        0.06
14:00:00        694               595      44           0.01        0.05
09:00:00        658               566      39           0.01        0.05
16:30:00        652               572      38           0.01        0.06
10:00:00        649               560      39           0.01        0.06
12:00:00        636               559      40           0.01        0.06
15:30:00        635               553      46           0.01        0.06
11:00:00        608               512      39           0.01        0.05
13:00:00        605               503      47           0.01        0.06
20:30:00        603               506      80           0.01        0.12
21:00:00        596               472      66           0.01        0.11
08:30:00        589               509      30           0.01        0.03
14:30:00        584               497      39           0.01        0.05
06:00:00        549               439      60           0.01        0.09
22:00:00        527               420      51           0.01        0.09
10:30:00        526               447      20           0.01        0.03
09:30:00        524               442      25           0.01        0.04
13:30:00        520               449      35           0.01        0.06
18:40:00        519               460      47           0.01        0.09

In [69]:
def ranking_fase_dia(var):
    t = (
        prf_acidentes_2025
        .groupby(var)
        .agg(
            acidentes=("fase_dia", "count"),
            acidentes_graves=("acidente_grave", "sum"),
            mortos=("mortos", "sum"),
        )
        .sort_values("acidentes", ascending=False)
    )
    t["pct_acidentes"] = t["acidentes"] / total_acidentes
    t["pct_fatais"] = (
        prf_acidentes_2025.groupby(var)["acidente_fatal"].sum() / t["acidentes"]
    )
    return t

ranking_fase_dia("fase_dia").head(30)

             acidentes  acidentes_graves  mortos  pct_acidentes  pct_fatais
fase_dia
Pleno dia        40375             35034    2391           0.56        0.05
Plena Noite      24781             20239    2892           0.34        0.10
Anoitecer         3926              3359     288           0.05        0.06
Amanhecer         3447              2758     472           0.05        0.11

In [70]:
def ranking_sentido(var):
    t = (
        prf_acidentes_2025
        .groupby(var)
        .agg(
            acidentes=("sentido_via", "count"),
            acidentes_graves=("acidente_grave", "sum"),
            mortos=("mortos", "sum"),
        )
        .sort_values("acidentes", ascending=False)
    )
    t["pct_acidentes"] = t["acidentes"] / total_acidentes
    t["pct_fatais"] = (
        prf_acidentes_2025.groupby(var)["acidente_fatal"].sum() / t["acidentes"]
    )
    return t

ranking_sentido("sentido_via").head(30)

               acidentes  acidentes_graves  mortos  pct_acidentes  pct_fatais
sentido_via
Crescente          38715             32890    3408           0.53        0.08
Decrescente        33647             28453    2635           0.46        0.07
Não Informado        167                47       0           0.00        0.00

In [71]:
def ranking_uf(var):
    t = (
        prf_acidentes_2025
        .groupby(var)
        .agg(
            acidentes=("uf", "count"),
            acidentes_graves=("acidente_grave", "sum"),
            mortos=("mortos", "sum"),
        )
        .sort_values("acidentes", ascending=False)
    )
    t["pct_acidentes"] = t["acidentes"] / total_acidentes
    t["pct_fatais"] = (
        prf_acidentes_2025.groupby(var)["acidente_fatal"].sum() / t["acidentes"]
    )
    return t

ranking_uf("uf").head(30)

    acidentes  acidentes_graves  mortos  pct_acidentes  pct_fatais
uf
MG       9570              8363     765           0.13        0.07
SC       8186              7027     434           0.11        0.05
PR       7630              6292     593           0.11        0.07
RJ       6428              5741     330           0.09        0.05
RS       4899              4014     327           0.07        0.06
SP       4683              3984     221           0.06        0.04
BA       4108              3505     583           0.06        0.12
GO       3196              2562     308           0.04        0.08
PE       3013              2484     336           0.04        0.10
ES       2642              2418     161           0.04        0.05
MT       2636              2079     243           0.04        0.08
PB       1978              1691     142           0.03        0.06
MS       1654              1284     150           0.02        0.08
RN       1648              1450     111           0.02        0.06
PI       1490              1268     168           0.02        0.10
RO       1452              1199     102           0.02        0.06
CE       1302              1102     171           0.02        0.12
MA       1262              1043     281           0.02        0.19
PA       1117               886     224           0.02        0.17
DF       1011               818      47           0.01        0.04
TO        677               578     102           0.01        0.12
AL        629               533      96           0.01        0.14
SE        589               471      51           0.01        0.07
AC        280               241      29           0.00        0.10
AP        169               148      14           0.00        0.05
RR        142               112      28           0.00        0.16
AM        138                97      26           0.00        0.14

In [72]:
def ranking_br(var):
    t = (
        prf_acidentes_2025
        .groupby(var)
        .agg(
            acidentes=("br", "count"),
            acidentes_graves=("acidente_grave", "sum"),
            mortos=("mortos", "sum"),
        )
        .sort_values("acidentes", ascending=False)
    )
    t["pct_acidentes"] = t["acidentes"] / total_acidentes
    t["pct_fatais"] = (
        prf_acidentes_2025.groupby(var)["acidente_fatal"].sum() / t["acidentes"]
    )
    return t

ranking_br("br").head(30)

     acidentes  acidentes_graves  mortos  pct_acidentes  pct_fatais
br
101      13014             11355     760           0.18        0.05
116      11021              9436     708           0.15        0.06
40        3502              3054     214           0.05        0.05
381       3496              3040     190           0.05        0.05
153       2789              2268     282           0.04        0.08
163       2519              1945     210           0.03        0.07
364       2264              1859     173           0.03        0.07
277       2157              1746     152           0.03        0.06
262       1769              1484     169           0.02        0.08
376       1762              1441     121           0.02        0.06
230       1745              1497     192           0.02        0.10
470       1388              1201     123           0.02        0.07
282       1379              1136     100           0.02        0.06
316       1236              1052     201           0.02        0.15
70        1084               883      86           0.01        0.07
60        1081               899      75           0.01        0.06
324        942               800      63           0.01        0.06
369        915               814      72           0.01        0.07
280        902               811      46           0.01        0.04
232        830               683     105           0.01        0.12
290        768               624      40           0.01        0.04
50         751               617      42           0.01        0.05
343        742               630      51           0.01        0.06
20         699               541      69           0.01        0.08
158        683               555      82           0.01        0.11
386        623               520      60           0.01        0.08
365        600               503      87           0.01        0.12
222        581               494     128           0.01        0.18
135        559               444     105           0.01        0.15
10         506               432      95           0.01        0.17

In [41]:
def ranking_veiculos(var):
    t = (
        prf_acidentes_2025
        .groupby(var)
        .agg(
            acidentes=("veiculos", "count"),
            acidentes_graves=("acidente_grave", "sum"),
            mortos=("mortos", "sum"),
        )
        .sort_values("acidentes", ascending=False)
    )
    t["pct_acidentes"] = t["acidentes"] / total_acidentes
    t["pct_fatais"] = (
        prf_acidentes_2025.groupby(var)["acidente_fatal"].sum() / t["acidentes"]
    )
    return t

ranking_veiculos("veiculos").head(30)

          acidentes  acidentes_graves  mortos  pct_acidentes  pct_fatais
veiculos
2             35070             30706    2893           0.48        0.07
1             23617             18920     934           0.33        0.04
3              8623              7311    1128           0.12        0.11
4              3002              2495     557           0.04        0.15
5              1285              1146     312           0.02        0.18
6               437               378      97           0.01        0.15
7               224               196      48           0.00        0.17
8               114                99      25           0.00        0.17
9                68                63      25           0.00        0.28
10               23                22       5           0.00        0.22
11               22                20       7           0.00        0.27
12               16                15       3           0.00        0.12
13               14                 8       4           0.00        0.29
14                5                 5       1           0.00        0.20
15                2                 1       1           0.00        0.50
18                2                 1       1           0.00        0.50
16                1                 1       1           0.00        1.00
17                1                 1       0           0.00        0.00
21                1                 1       1           0.00        1.00
31                1                 1       0           0.00        0.00
82                1                 0       0           0.00        0.00

#### Análise dos Rankings

Leitura: Os rankings permitem identificar a distribuição dos acidentes de trânsito segundo diferentes características temporais, administrativas e da ocorrência. A análise por dia da semana e horário evidencia os períodos com maior concentração de registros.

Os rankings por fase do dia, sentido da via, UF e BR ajudam a compreender a distribuição geográfica e operacional dos acidentes. Além disso, a quantidade de veículos permite observar a concentração de ocorrências com diferentes níveis de envolvimento veicular.

A comparação entre a participação percentual de cada categoria e os indicadores globais auxilia na identificação de padrões de frequência e gravidade. Esses resultados devem ser interpretados como associações observadas na base, sem afirmar causalidade.

#### Dia da Semana

Dia da semana: os dias posicionados no topo do ranking concentram a maior parcela dos acidentes registrados. Uma possível hipótese é que diferenças no fluxo de veículos e nos deslocamentos ao longo da semana influenciem essa distribuição.

#### Horário

Horários com maior número de acidentes podem estar relacionados a períodos de maior circulação de veículos, como deslocamentos de trabalho e retorno para casa. Entretanto, sem dados de fluxo por hora, não é possível interpretar a frequência como risco individual.

#### Fase do Dia

A distribuição por fase do dia permite comparar amanhecer, pleno dia, anoitecer e plena noite. Diferenças podem estar relacionadas à visibilidade e ao volume de circulação, mas outros fatores também podem explicar o padrão.

#### Sentido da Via, UF e BR

Os rankings por sentido da via, UF e BR permitem identificar concentrações operacionais e geográficas. Rodovias ou estados com muitos acidentes também podem possuir maior extensão ou maior fluxo, portanto o volume absoluto não representa sozinho o risco.

#### Quantidade de Veículos

A comparação pela quantidade de veículos mostra a participação de acidentes individuais e de ocorrências envolvendo múltiplos veículos. Categorias com maior número de veículos podem apresentar diferentes padrões de gravidade, mas essa associação não demonstra causa e efeito.

#### Série Mensal

- #### Criação da coluna "mẽs" no formato Ano-Mês (ex: 2025-01)

In [42]:
# Agrupa cada acidente no seu respectivo mês, servindo como base para a analise da série temporal 
prf_acidentes_2025["mes"] = (
    
    prf_acidentes_2025["data_inversa"]
    .dt.to_period("M").astype(str)
)

- #### Agrupamento dos acidentes por mês

In [43]:
# Calcula simultaneamente a quantidade total de acidentes,
# acidentes graves e acidentes com múltiplos veículos
serie_mensal = prf_acidentes_2025.groupby("mes").agg(
    acidentes=("id", "count"),
    acidentes_graves=("acidente_grave", "sum"),
    multiplos_veiculos=("multiplos_veiculos", "sum"),
    mortos=("mortos", "sum")
)

- #### Cálculo do percentual mensal de acidentes graves

In [44]:
# Permite observar se a proporção de acidentes graves
# oscila ao longo dos meses
serie_mensal["pct_graves"] = (
    serie_mensal["acidentes_graves"] /
    serie_mensal["acidentes"]
)

- #### Taxa de mortalidade

In [45]:
serie_mensal["taxa_mortalidade"] = (
    
    prf_acidentes_2025.groupby("mes")["mortos"].sum() / serie_mensal["acidentes"]
)

- #### ìndice de gravidade

In [46]:
serie_mensal["indice_gravidade"] = (
    
    prf_acidentes_2025.groupby("mes").apply(
        
        lambda prf_acidentes_2025: (prf_acidentes_2025["mortos"].sum()*3 +
                                    prf_acidentes_2025["feridos_graves"].sum() * 2
                                   + prf_acidentes_2025["feridos_leves"].sum() * 1)
    ) / serie_mensal["acidentes"]
)

In [47]:
serie_mensal

,acidentes,acidentes_graves,multiplos_veiculos,mortos,pct_graves,taxa_mortalidade,indice_gravidade
mes,,,,,,,
2025-01,5528,4722,3624,418,0.85,0.08,1.76
2025-02,5287,4465,3524,412,0.84,0.08,1.62
2025-03,5960,5023,3942,462,0.84,0.08,1.64
2025-04,5786,4910,3998,495,0.85,0.09,1.69
2025-05,6096,5186,4142,574,0.85,0.09,1.68
2025-06,6122,5163,4230,528,0.84,0.09,1.67
2025-07,6238,5262,4332,536,0.84,0.09,1.69
2025-08,6246,5247,4241,554,0.84,0.09,1.65
2025-09,6017,5103,4125,500,0.85,0.08,1.67
2025-10,6252,5328,4255,494,0.85,0.08,1.68
2025-11,6209,5253,4103,498,0.85,0.08,1.66
2025-12,6788,5728,4396,572,0.84,0.08,1.72

#### Limitação Importante:

Limitação importante: Os indicadores apresentados são agregados por hora do dia e, portanto, não permitem identificar quais fatores específicos contribuíram para a ocorrência ou gravidade dos acidentes em cada horário. Além disso, a taxa de mortalidade e o índice de gravidade são indicadores gerais e não estabelecem, isoladamente, uma relação de causa e efeito. A interpretação também depende da definição utilizada para cada indicador e da qualidade da classificação dos acidentes. Por fim, a quantidade de acidentes registrada em cada horário pode estar relacionada ao volume de veículos circulando naquele período, informação que não está sendo considerada diretamente nesta análise.

Leitura: A série por hora permite acompanhar a distribuição dos acidentes ao longo das 24 horas do dia e comparar a quantidade total de ocorrências com os acidentes graves e fatais. Observa-se uma variação no volume de acidentes entre os diferentes horários, permitindo identificar períodos de maior concentração de ocorrências. Essa análise serve como referência para identificar os horários mais críticos e direcionar análises posteriores por dia da semana, fase do dia, sentido da via, UF, BR e quantidade de veículos envolvidos.

- #### Percentual de acidentes com múltiplos veículos

In [48]:
# Calcula a proporção mensal de acidentes com dois ou mais veículos
serie_mensal["pct_multiplos_veiculos"] = (
    serie_mensal["multiplos_veiculos"] / serie_mensal["acidentes"]
)

In [49]:
# Mantém o indicador mensal já calculado para comparação entre os meses

In [50]:
# A variável multiplos_veiculos já foi criada no Bloco 1 e é reutilizada aqui.

In [51]:
# Recalcula a série mensal com a nova variável de interesse
serie_mensal = prf_acidentes_2025.groupby("mes").agg(
    acidentes=("id", "count"),
    acidentes_graves=("acidente_grave", "sum"),
    multiplos_veiculos=("multiplos_veiculos", "sum"),
    mortos=("mortos", "sum")
)

In [52]:
serie_mensal["pct_multiplos_veiculos"] = serie_mensal["multiplos_veiculos"] / serie_mensal["acidentes"]

In [53]:
serie_mensal

,acidentes,acidentes_graves,multiplos_veiculos,mortos,pct_multiplos_veiculos
mes,,,,,
2025-01,5528,4722,3624,418,0.66
2025-02,5287,4465,3524,412,0.67
2025-03,5960,5023,3942,462,0.66
2025-04,5786,4910,3998,495,0.69
2025-05,6096,5186,4142,574,0.68
2025-06,6122,5163,4230,528,0.69
2025-07,6238,5262,4332,536,0.69
2025-08,6246,5247,4241,554,0.68
2025-09,6017,5103,4125,500,0.69
2025-10,6252,5328,4255,494,0.68
2025-11,6209,5253,4103,498,0.66
2025-12,6788,5728,4396,572,0.65

- Uma limitação importante é que a tabela apresenta apenas os valores agregados por mês, não permitindo identificar quais características específicas explicam as diferenças entre os períodos. A análise mostra associação e distribuição, não causalidade.

### - Análise bivariada focada no alvo

#### Este é o coração da EDA.

- Comparamos cada variável explicativa com acidentes_fatais, sempre relatando volume e proporção - nunca só uma das duas

In [54]:
#### Criação de uma variável-alvo binária: acidente com vítimas fatais (1) ou não (0) 
prf_acidentes_2025["acidente_fatal"] = prf_acidentes_2025["classificacao_acidente"].fillna("").apply(
    lambda x: 1 if any(p in x.lower() for p in ["fatais", "fatal", "óbito", "morte"]) else 0
)

- Definição da função de análise bivariada adaptada para a base da PRF
*** var: variável explicativa (ex: "uf", "causa_acidente" etc.) 
*** min_acidentes: mínimo de acidentes para inclusão na análise (evita categorias irrelevantes)

In [55]:
def analise_bivariada_prf(prf_acidentes_2025, var, min_acidentes=1): 
    
    tab = prf_acidentes_2025.groupby(var).agg(
        
        # total de acidentes na categoria
        acidentes_total=("id", "count"), 
        
        # total de acidentes com vítimas fatais na categoria
        acidentes_fatais=("acidente_fatal", "sum"), 
        
        # total de mortes na categoria 
        mortos=("mortos", "sum"), 
        
        # total de feridos na categoria
        feridos=("feridos", "sum")
    )
    
    ### proporção condicional de acidente fatal
    tab["pct_acidente_fatal"] = tab["acidentes_fatais"] / tab["acidentes_total"]  
    
    ### filtro opcional de volume mínimo 
    tab = tab[tab["acidentes_total"] >= min_acidentes] 
    
    return tab.sort_values("pct_acidente_fatal", ascending = False)

In [56]:
#### Exemplo de uso com algumas variáveis explicativas
variaveis_explicativas = ["dia_semana", "horario", "fase_dia", "sentido_via"]

In [57]:
for var in variaveis_explicativas: 
    
    print(f"=== {var} x acidente_fatal ===") 
    display(analise_bivariada_prf(prf_acidentes_2025, var).head(10)) 
    print()

=== dia_semana x acidente_fatal ===

,acidentes_total,acidentes_fatais,mortos,feridos,pct_acidente_fatal
dia_semana,,,,,
domingo,11470,1017,1183,13729,0.09
sábado,11554,953,1120,13220,0.08
sexta-feira,11197,766,907,13057,0.07
quinta-feira,9405,625,694,10677,0.07
terça-feira,9062,586,681,10285,0.06
segunda-feira,10285,655,747,11763,0.06
quarta-feira,9556,607,711,10819,0.06

=== horario x acidente_fatal ===

,acidentes_total,acidentes_fatais,mortos,feridos,pct_acidente_fatal
horario,,,,,
21:37:00,1,1,1,0,1.00
04:27:00,1,1,1,0,1.00
04:37:00,1,1,1,0,1.00
01:26:00,1,1,1,0,1.00
01:56:00,1,1,1,0,1.00
00:09:00,2,2,4,2,1.00
23:24:00,1,1,1,1,1.00
02:06:00,1,1,3,0,1.00
04:09:00,3,2,6,42,0.67
00:38:00,3,2,2,2,0.67

=== fase_dia x acidente_fatal ===

,acidentes_total,acidentes_fatais,mortos,feridos,pct_acidente_fatal
fase_dia,,,,,
Amanhecer,3447,386,472,3761,0.11
Plena Noite,24781,2522,2892,27179,0.10
Anoitecer,3926,253,288,4558,0.06
Pleno dia,40375,2048,2391,48052,0.05

=== sentido_via x acidente_fatal ===

,acidentes_total,acidentes_fatais,mortos,feridos,pct_acidente_fatal
sentido_via,,,,,
Crescente,38715,2906,3408,45253,0.08
Decrescente,33647,2303,2635,38232,0.07
Não Informado,167,0,0,65,0.00

In [58]:
### Análise bivariada para 'veiculos'
display(analise_bivariada_prf(prf_acidentes_2025, "veiculos").head(10))

,acidentes_total,acidentes_fatais,mortos,feridos,pct_acidente_fatal
veiculos,,,,,
21,1,1,1,8,1.00
16,1,1,1,2,1.00
15,2,1,1,2,0.50
18,2,1,1,2,0.50
13,14,4,4,12,0.29
9,68,19,25,133,0.28
11,22,6,7,58,0.27
10,23,5,5,44,0.22
14,5,1,1,10,0.20
5,1285,229,312,1777,0.18

In [59]:
### Análise bivariada para 'fase_dia'
display(analise_bivariada_prf(prf_acidentes_2025, "fase_dia").head(10))

,acidentes_total,acidentes_fatais,mortos,feridos,pct_acidente_fatal
fase_dia,,,,,
Amanhecer,3447,386,472,3761,0.11
Plena Noite,24781,2522,2892,27179,0.10
Anoitecer,3926,253,288,4558,0.06
Pleno dia,40375,2048,2391,48052,0.05

In [60]:
### Análise bivariada para 'uf'
display(analise_bivariada_prf(prf_acidentes_2025, "uf").head(10))

    acidentes_total  acidentes_fatais  mortos  feridos  pct_acidente_fatal
uf
MA             1262               236     281     1295                0.19
PA             1117               193     224     1191                0.17
RR              142                23      28      193                0.16
AM              138                19      26      149                0.14
AL              629                86      96      740                0.14
TO              677                83     102      784                0.12
CE             1302               152     171     1429                0.12
BA             4108               476     583     5023                0.12
AC              280                29      29      328                0.10
PE             3013               302     336     3348                0.10

In [61]:
### Análise bivariada para 'br'
display(analise_bivariada_prf(prf_acidentes_2025, "br").head(10))

     acidentes_total  acidentes_fatais  mortos  feridos  pct_acidente_fatal
br
30                 4                 2       2        3                0.50
403                6                 3       3        2                0.50
416               13                 6       6       11                0.46
412               28                10      10       46                0.36
308               34                10      10       41                0.29
420               28                 8      10       40                0.29
402               63                16      23       69                0.25
447                8                 2       2        7                0.25
349               52                12      16       78                0.23
405               97                22      22       91                0.23

In [62]:
### Análise bivariada para 'regional'
display(analise_bivariada_prf(prf_acidentes_2025, "regional").head(10))

,acidentes_total,acidentes_fatais,mortos,feridos,pct_acidente_fatal
regional,,,,,
SPRF-MA,1230,232,277,1263,0.19
SPRF-PA,1070,187,218,1149,0.17
SPRF-RR,142,23,28,193,0.16
SPRF-AL,614,85,93,718,0.14
SPRF-AM,137,18,25,149,0.13
SPRF-TO,677,83,102,784,0.12
SPRF-BA,3990,465,572,4891,0.12
SPRF-CE,1311,151,170,1444,0.12
SPRF-AC,282,31,31,329,0.11
SPRF-PI,1522,153,172,1721,0.10

In [63]:
### Análise bivariada para 'sentido_via'
display(analise_bivariada_prf(prf_acidentes_2025, "sentido_via").head(10))

,acidentes_total,acidentes_fatais,mortos,feridos,pct_acidente_fatal
sentido_via,,,,,
Crescente,38715,2906,3408,45253,0.08
Decrescente,33647,2303,2635,38232,0.07
Não Informado,167,0,0,65,0.00

In [64]:
### Análise bivariada para 'pessoas'
display(analise_bivariada_prf(prf_acidentes_2025, "pessoas").head(10))

,acidentes_total,acidentes_fatais,mortos,feridos,pct_acidente_fatal
pessoas,,,,,
59,1,1,1,28,1.00
76,1,1,4,38,1.00
60,1,1,2,1,1.00
40,4,3,5,33,0.75
28,3,2,3,13,0.67
69,3,2,16,54,0.67
37,3,2,17,21,0.67
41,4,2,3,49,0.50
38,2,1,1,9,0.50
20,10,5,10,69,0.50

#### Achados observados na base PRF 2025

A análise bivariada permitiu identificar diferenças na proporção de acidentes fatais conforme o dia da semana, horário, fase do dia, sentido da via e características administrativas e da ocorrência.

Entre as categorias temporais, algumas podem apresentar proporções de fatalidade acima da média geral. Em relação à quantidade de veículos e pessoas, diferenças podem indicar contextos de ocorrência com maior ou menor gravidade, mas devem ser interpretadas junto ao volume de registros.

Na dimensão geográfica, a comparação entre UF, BR e regional pode indicar concentrações distintas de acidentes fatais. Categorias com poucos registros podem apresentar percentuais extremos sem representar um padrão robusto.

Esses resultados representam associações observadas nos dados, não permitindo afirmar, isoladamente, que uma 
determinada condição seja a causa dos acidentes fatais. Além disso, algumas categorias dos quadros de município, KM e traçado da via apresentaram taxas de 100%, porém com apenas um ou poucos acidentes registrados. Por isso, essas categorias devem ser interpretadas com cautela, pois o pequeno número de observações pode produzir percentuais elevados sem representar um padrão geral da população.

#### Quadro de cruzamento das análises bivariadas

In [65]:
dicionario = pd.DataFrame({
    'Cruzamento': ["dia_semana", "dia_semana", "horario", "horario", "fase_dia", "fase_dia", "sentido_via", "veiculos"],
    "Categoria": ["sábado", "domingo", "18:00:00", "17:00:00", "Plena Noite", "Pleno dia", "Crescente", "2"],
    "Interpretação": [
        "Comparação da proporção de acidentes fatais por dia da semana.",
        "Comparação da proporção de acidentes fatais por dia da semana.",
        "Comparação da proporção de acidentes fatais por horário.",
        "Comparação da proporção de acidentes fatais por horário.",
        "Comparação da proporção de acidentes fatais por fase do dia.",
        "Comparação da proporção de acidentes fatais por fase do dia.",
        "Comparação da proporção de acidentes fatais por sentido da via.",
        "Comparação da proporção de acidentes fatais por quantidade de veículos."
    ]
})

In [66]:
dicionario

    Cruzamento    Categoria                                      Interpretação
0   dia_semana       sábado  Comparação da proporção de acidentes fatais po...
1   dia_semana      domingo  Comparação da proporção de acidentes fatais po...
2      horario     18:00:00  Comparação da proporção de acidentes fatais po...
3      horario     17:00:00  Comparação da proporção de acidentes fatais po...
4     fase_dia  Plena Noite  Comparação da proporção de acidentes fatais po...
5     fase_dia    Pleno dia  Comparação da proporção de acidentes fatais po...
6  sentido_via    Crescente  Comparação da proporção de acidentes fatais po...
7     veiculos            2  Comparação da proporção de acidentes fatais po...